$AssertFunction = Exit[17]&;
Get["test/arithmetic.m"];
Get["test/algebra.m"];
Get["test/part.m"];
Get["test/function.m"];
Get["test/derivative.m"];
Get["test/pattern.m"];
Get["test/parse.m"];
Get["test/modular_subgroups.m"];
Print["passed"];
Exit[0];
